version: '3'
services:
  golang:
    container_name: gin_todo_app
    build:
      context: .
      dockerfile: ./docker/local/golang/Dockerfile
    volumes:
      - .:/go/src
    tty: true
    ports:
      - "3000:3000"
    environment:
        TZ: Asia/Tokyo