version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/local/go/Dockerfile
    tty: true
    volumes:
      - ./src:/go/src
    ports:
      - "3000:3000"
    environment:
        TZ: Asia/Tokyo