version: '3'
services:
  golang:
    container_name: gin_todo_app
    build:
      context: .
      dockerfile: ./docker/local/golang/Dockerfile
    volumes:
      - .:/go/src
    tty: true
    ports:
      - "${PORT}:${PORT}"
    environment:
      TZ: Asia/Tokyo
      DSN: ${DSN}
      PORT: ${PORT}

  db:
    container_name: gin_todo_app_db
    build:
      context: .
      dockerfile: ./docker/local/mysql/Dockerfile
    platform: linux/x86_64
    volumes:
      - ./docker/local/mysql/sqls:/docker-entrypoint-initdb.d
      - ./docker/local/mysql/data:/var/lib/mysql
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
    - ${LOCAL_DB_PORT}:${CONTAINER_DB_PORT}